### 장소 추천 API - 모든 장소
GET http://localhost:8080/api/v1/places?station-name=강남역&address=서울 강남구 강남대로 396


### 장소 추천 API - 음식점
GET http://localhost:8080/api/v1/places?station-name=강남역&address=서울 강남구 강남대로 396&category=RESTAURANT


### 장소 추천 API - 카페
GET http://localhost:8080/api/v1/places?station-name=강남역&address=서울 강남구 강남대로 396&category=CAFE


### 모임 생성 API
POST http://localhost:8080/api/v1/groups?member-id={memberId}
Content-Type: application/json

{
  "capacity": 2
}

<> 2023-03-01T144358.400.json

### 모임 단건 조회 API
GET http://localhost:8080/api/v1/groups/{groupId}



### [TEST] 더미 회원 생성 API
POST http://localhost:8080/api/test/members?nickname=nickname1


### [TEST] 모든 모임 조회 API
GET http://localhost:8080/api/test/groups?member-id=1


### [TEST] 모임 생성 API
POST http://localhost:8080/api/test/groups?member-id=1
Content-Type: application/json

{
  "capacity": 2
}


### [TEST] 모임 상세 조회 API
GET http://localhost:8080/api/test/groups/aa9de2b4-5901-44ea-8bbd-a5cdd377c0c6


### [TEST] 모임 삭제 API
DELETE http://localhost:8080/api/test/groups/6b3543db-3a4e-4fbf-8839-696847576511

