### 장소 추천 API - 모든 장소
GET http://localhost:8080/api/v1/places?station-name=강남역&page=0&size=3


### 장소 추천 API - 음식점
GET http://localhost:8080/api/v1/places?station-name=강남역&category=RESTAURANT&page=0&size=3


### 장소 추천 API - 카페
GET http://localhost:8080/api/v1/places?station-name=강남역&category=CAFE&page=0&size=3

### 모임 생성 API
POST http://localhost:8080/api/v1/groups?member-id={memberId}
Content-Type: application/json

{
  "capacity": 2
}

### 모임 단건 조회 API
GET http://localhost:8080/api/v1/groups/{groupId}


### [TEST] 더미 회원 생성 API
POST http://localhost:8080/api/test/members?nickname=nickname1


### [TEST] 모든 모임 조회 API
GET http://localhost:8080/api/test/groups?member-id=1


### [TEST] 모임 생성 API
POST http://localhost:8080/api/test/groups?member-id=1
Content-Type: application/json

{
  "capacity": 4
}


### [TEST] 모임 상세 조회 API
GET http://localhost:8080/api/test/groups/e82c47b0-149f-4018-bf8d-52b2f4184eb1


### [TEST] 모임 삭제 API
DELETE http://localhost:8080/api/test/groups/6b3543db-3a4e-4fbf-8839-696847576511


### 모임 출발지 입력
PATCH http://localhost:8080/api/v1/mid-points/starts?memberId=1
Content-Type: application/json

{
  "groupId": "4b5377bf-e8c1-4882-9087-6890d18eaf15",
  "stationName": "강남역",
  "lat": 1.123123,
  "lng": 11.123123
}
