name: springboot-gradle-docker-ec2-cd

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set YML for release
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: Build with Gradle
        run: ./gradlew bootJar

      # Spring 어플리케이션 Docker Image 빌드 & 도커 허브로 도커이미지 푸시
      - name: Build Docker Image For Spring
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/odeego .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/odeego 

      # 서버에서 Docker 이미지 실행
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            docker stop odeego
            docker rm odeego
            docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/odeego
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/odeego
            docker-compose up -d